# gem 'pg'

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  url: postgresql://localhost/michelle_development

test:
  <<: *default
  url: postgresql://localhost/michelle_test

production:
  url: <%= ENV['DATABASE_URL'] %>
